[dependencies]

[package]
  cjc-version = "0.59.6"
  compile-option = ""
  description = "json macho for cangjie"
  link-option = ""
  name = "json_cj"
  output-type = "static"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
