name: Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: Zxilly/setup-cangjie@v1.0.1
        with:
          token: ${{ secrets.GITCODE_TOKEN }}

      - name: Run tests
        if: matrix.os == 'windows-latest'
        run: |
          cjpm test

      - name: Run tests
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          source $CANGJIE_HOME/envsetup.sh
          cjpm test