name: Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4

      - uses: Zxilly/setup-cangjie@v1.2.0
        with:
          token: ${{ secrets.GITCODE_TOKEN }}

      - name: Run tests
        shell: bash
        run: |
          source $CANGJIE_HOME/envsetup.sh
          cjpm test --coverage
          cjcov -k
      
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.0
        with:
          format: gcov