name: Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4

      - uses: Zxilly/setup-cangjie@v1.2.1
        with:
          token: ${{ secrets.GITCODE_TOKEN }}

      - name: Run tests
        shell: bash
        run: |
          cjpm test --coverage
          cjcov -k
          python scripts/clean.py
      
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          plugin: gcov