name: Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4

      - uses: Zxilly/setup-cangjie@v1.2.1
        with:
          token: ${{ secrets.GITCODE_TOKEN }}

      - name: Run tests
        shell: bash
        run: |
          source $CANGJIE_HOME/envsetup.sh
          cjpm test --coverage
          cjcov -k
          python scripts/clean.py
      
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.0
        with:
          format: gcov
          parallel: true
          flag-name: ${{ matrix.os }}
  
  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2.3.0
      with:
        parallel-finished: true
        carryforward: "ubuntu-latest,macos-13,macos-14,windows-latest"